# ============================================================================
# Kustomization — Production Overlay
# ============================================================================
# ArgoCD watches this overlay. The CI pipeline updates `newTag` on each push.
# ============================================================================
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: rso

resources:
  - ../../base

images:
  - name: ghcr.io/isuru709/rso-frontend
    newTag: 69ba9720219b1900032a4111ecc84769a1f9c39e
  - name: ghcr.io/isuru709/rso-tenant-service
    newTag: 69ba9720219b1900032a4111ecc84769a1f9c39e
  - name: ghcr.io/isuru709/rso-user-service
    newTag: 69ba9720219b1900032a4111ecc84769a1f9c39e
  - name: ghcr.io/isuru709/rso-resource-service
    newTag: 69ba9720219b1900032a4111ecc84769a1f9c39e
  - name: ghcr.io/isuru709/rso-booking-service
    newTag: 69ba9720219b1900032a4111ecc84769a1f9c39e
  - name: ghcr.io/isuru709/rso-notification-service
    newTag: 69ba9720219b1900032a4111ecc84769a1f9c39e
