# ============================================================================
# Kustomization — Production Overlay
# ============================================================================
# ArgoCD watches this overlay. The CI pipeline updates `newTag` on each push.
# ============================================================================
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: rso

resources:
  - ../../base

images:
  - name: ghcr.io/isuru709/rso-frontend
    newTag: f1714853fc321d87a4841a9e7d18d1f34320f9dc
  - name: ghcr.io/isuru709/rso-tenant-service
    newTag: f1714853fc321d87a4841a9e7d18d1f34320f9dc
  - name: ghcr.io/isuru709/rso-user-service
    newTag: f1714853fc321d87a4841a9e7d18d1f34320f9dc
  - name: ghcr.io/isuru709/rso-resource-service
    newTag: f1714853fc321d87a4841a9e7d18d1f34320f9dc
  - name: ghcr.io/isuru709/rso-booking-service
    newTag: f1714853fc321d87a4841a9e7d18d1f34320f9dc
  - name: ghcr.io/isuru709/rso-notification-service
    newTag: f1714853fc321d87a4841a9e7d18d1f34320f9dc
