# ============================================================================
# Kustomization — Production Overlay
# ============================================================================
# ArgoCD watches this overlay. The CI pipeline updates `newTag` on each push.
# ============================================================================
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: rso

resources:
  - ../../base

images:
  - name: ghcr.io/isuru709/rso-frontend
    newTag: bfcc849de690deff4d2eb761faf8c07e95c9e682
  - name: ghcr.io/isuru709/rso-tenant-service
    newTag: bfcc849de690deff4d2eb761faf8c07e95c9e682
  - name: ghcr.io/isuru709/rso-user-service
    newTag: bfcc849de690deff4d2eb761faf8c07e95c9e682
  - name: ghcr.io/isuru709/rso-resource-service
    newTag: bfcc849de690deff4d2eb761faf8c07e95c9e682
  - name: ghcr.io/isuru709/rso-booking-service
    newTag: bfcc849de690deff4d2eb761faf8c07e95c9e682
  - name: ghcr.io/isuru709/rso-notification-service
    newTag: bfcc849de690deff4d2eb761faf8c07e95c9e682
